import Image from "next/image";
import MyHello from "./components/MyHello";
export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <MyHello />
    </>
  );
}
